apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.operatorPrivateKeyKubernetes | quote}}
  namespace: default
type: Opaque
data:
  access-key: YWJjZA==  # Base64-encoded value of "abcd"
  secret-access-key: ZGVmZw==  # Base64-encoded value of "defg"